export const MENUITEMS = [
  {
    title: 'Dashboard',
    icon: Home,
    type: 'link',
    path: '/',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Transactions',
    icon: BarChart2,
    type: 'link',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Wallet',
    icon: CreditCard,
    type: 'link',
    path: '/wallet',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Transfers',
    icon: RefreshCw,
    type: 'link',
    path: '/transfer',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Invoice',
    path: '/dashboard/default',
    icon: BookOpen,
    type: 'link',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Issuing',
    icon: Upload,
    type: 'link',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Settings',
    icon: Settings,
    type: 'link',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
  {
    title: 'Api Docs',
    icon: File,
    type: 'link',
    badgeType: 'primary',
    active: false,
    // children: [{ path: '/dashboard/default', title: 'Default', type: 'link' }],
  },
];
